In [1]:
import pandas as pd
import zipfile

# North Carolina listing df
df=pd.read_csv("../data/raw/listings.csv.zip")
# North Carolina calendar df
ca=pd.read_csv("../data/raw/calendar.csv.zip")

In [2]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,108061,https://www.airbnb.com/rooms/108061,20230319041221,2023-03-19,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,Walk to town in ten minutes! Monthly rental in...,"I love my neighborhood! Its friendly, easy-goi...",https://a0.muscache.com/pictures/miso/Hosting-...,320564,...,4.80,4.84,4.49,NaN,f,2,2,0,0,0.66
1,155305,https://www.airbnb.com/rooms/155305,20230319041221,2023-03-19,city scrape,Cottage! BonPaul + Sharky's Hostel,<b>The space</b><br />Pet friendly private cot...,"We are within easy walk of pubs, breweries, mu...",https://a0.muscache.com/pictures/8880711/cf38d...,746673,...,4.74,4.93,4.55,NaN,f,6,1,2,3,2.70
2,156805,https://www.airbnb.com/rooms/156805,20230319041221,2023-03-19,previous scrape,"Private Room ""Ader"" at BPS Hostel",<b>The space</b><br />Private Rooms at Bon Pau...,"Easy walk to pubs, cafes, bakery, breweries, l...",https://a0.muscache.com/pictures/23447d55-fa7e...,746673,...,4.61,4.84,4.46,NaN,t,6,1,2,3,0.48
3,197263,https://www.airbnb.com/rooms/197263,20230319041221,2023-03-19,city scrape,Tranquil Room & Private Bath,"This is a comfy, peaceful and clean room with ...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,961396,...,4.92,4.82,4.98,NaN,f,2,1,1,0,0.51
4,209068,https://www.airbnb.com/rooms/209068,20230319041221,2023-03-19,city scrape,Terrace Cottage,Located in one of Asheville's oldest historic ...,Our beautiful Grove Park Historic District clo...,https://a0.muscache.com/pictures/1829924/9f3bf...,1029919,...,4.98,4.93,4.77,NaN,f,1,1,0,0,0.43

In [3]:
ca.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,108061,2023-03-19,f,$100.00,$100.00,30,1125
1,108061,2023-03-20,f,$100.00,$100.00,30,1125
2,108061,2023-03-21,f,$100.00,$100.00,30,1125
3,108061,2023-03-22,f,$100.00,$100.00,30,1125
4,108061,2023-03-23,f,$100.00,$100.00,30,1125

In [4]:
merged_df=pd.merge(df, ca, left_on='id', right_on='listing_id', how='left')
merged_df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,listing_id,date,available,price_y,adjusted_price,minimum_nights_y,maximum_nights_y
0,108061,https://www.airbnb.com/rooms/108061,20230319041221,2023-03-19,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,Walk to town in ten minutes! Monthly rental in...,"I love my neighborhood! Its friendly, easy-goi...",https://a0.muscache.com/pictures/miso/Hosting-...,320564,...,0,0,0.66,108061,2023-03-19,f,$100.00,$100.00,30,1125
1,108061,https://www.airbnb.com/rooms/108061,20230319041221,2023-03-19,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,Walk to town in ten minutes! Monthly rental in...,"I love my neighborhood! Its friendly, easy-goi...",https://a0.muscache.com/pictures/miso/Hosting-...,320564,...,0,0,0.66,108061,2023-03-20,f,$100.00,$100.00,30,1125
2,108061,https://www.airbnb.com/rooms/108061,20230319041221,2023-03-19,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,Walk to town in ten minutes! Monthly rental in...,"I love my neighborhood! Its friendly, easy-goi...",https://a0.muscache.com/pictures/miso/Hosting-...,320564,...,0,0,0.66,108061,2023-03-21,f,$100.00,$100.00,30,1125
3,108061,https://www.airbnb.com/rooms/108061,20230319041221,2023-03-19,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,Walk to town in ten minutes! Monthly rental in...,"I love my neighborhood! Its friendly, easy-goi...",https://a0.muscache.com/pictures/miso/Hosting-...,320564,...,0,0,0.66,108061,2023-03-22,f,$100.00,$100.00,30,1125
4,108061,https://www.airbnb.com/rooms/108061,20230319041221,2023-03-19,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,Walk to town in ten minutes! Monthly rental in...,"I love my neighborhood! Its friendly, easy-goi...",https://a0.muscache.com/pictures/miso/Hosting-...,320564,...,0,0,0.66,108061,2023-03-23,f,$100.00,$100.00,30,1125

In [5]:
merged_df = merged_df.drop(columns=['listing_url','scrape_id','last_scraped', 'description','neighborhood_overview','picture_url','host_url','host_name',
                                    'host_about','host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 
                                    'host_total_listings_count', 'host_verifications','host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
                                    'neighbourhood_cleansed', 'neighbourhood_group_cleansed'])

In [6]:
merged_df = merged_df.drop(columns=['listing_id', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication',
                                    'review_scores_location', 'review_scores_value', 'license'])

In [7]:
merged_df = merged_df.drop(columns=['minimum_minimum_nights', 'maximum_minimum_nights','minimum_maximum_nights', 'maximum_maximum_nights',
                                    'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated','has_availability', 'availability_30', 
                                    'availability_60','availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews_ltm', 
                                    'number_of_reviews_l30d','first_review', 'last_review', 'instant_bookable','minimum_nights_y', 'maximum_nights_y'])

In [8]:
merged_df = merged_df.drop(columns=['price_y', 'adjusted_price', 'bathrooms_text', 'bathrooms'])

In [9]:
merged_df.head()

,id,source,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,latitude,...,maximum_nights_x,number_of_reviews,review_scores_rating,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,date,available
0,108061,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,2010-12-16,"Asheville, NC",within an hour,100%,71%,35.6067,...,365,92,4.51,2,2,0,0,0.66,2023-03-19,f
1,108061,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,2010-12-16,"Asheville, NC",within an hour,100%,71%,35.6067,...,365,92,4.51,2,2,0,0,0.66,2023-03-20,f
2,108061,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,2010-12-16,"Asheville, NC",within an hour,100%,71%,35.6067,...,365,92,4.51,2,2,0,0,0.66,2023-03-21,f
3,108061,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,2010-12-16,"Asheville, NC",within an hour,100%,71%,35.6067,...,365,92,4.51,2,2,0,0,0.66,2023-03-22,f
4,108061,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,2010-12-16,"Asheville, NC",within an hour,100%,71%,35.6067,...,365,92,4.51,2,2,0,0,0.66,2023-03-23,f

In [10]:
# rename
merged_df=merged_df.rename(columns={"price_x":"price",'minimum_nights_x':'minimum_nights', 'maximum_nights_x':'maximum_nights'})
merged_df.columns

Index(['id', 'source', 'name', 'host_id', 'host_since', 'host_location',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'latitude', 'longitude', 'property_type', 'room_type', 'accommodates',
       'bedrooms', 'beds', 'amenities', 'price', 'minimum_nights',
       'maximum_nights', 'number_of_reviews', 'review_scores_rating',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month',
       'date', 'available'],
      dtype='object')

In [11]:
# remove $ in price column
merged_df['price'] = merged_df['price'].str.replace(',', '').str.replace('$', '')
merged_df['price'] = merged_df['price'].astype(float)
merged_df['price']

/var/folders/lc/5bgvdqzs30316llbpd2nwp1h0000gn/T/ipykernel_14442/2939112258.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  merged_df['price'] = merged_df['price'].str.replace(',', '').str.replace('$', '')

0          100.0
1          100.0
2          100.0
3          100.0
4          100.0
           ...
1153760     62.0
1153761     62.0
1153762     62.0
1153763     62.0
1153764     62.0
Name: price, Length: 1153765, dtype: float64

In [12]:
# column types
merged_df.dtypes

id                                                int64
source                                           object
name                                             object
host_id                                           int64
host_since                                       object
host_location                                    object
host_response_time                               object
host_response_rate                               object
host_acceptance_rate                             object
latitude                                        float64
longitude                                       float64
property_type                                    object
room_type                                        object
accommodates                                      int64
bedrooms                                        float64
beds                                            float64
amenities                                        object
price                                           float64
minimum_nights                                    int64
maximum_nights                                    int64
number_of_reviews                                 int64
review_scores_rating                            float64
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
date                                             object
available                                        object
dtype: object

In [13]:
len(merged_df)

1153765

In [14]:
# check if there are negative numbers
numeric_cols=merged_df.select_dtypes(include=['int', 'float']).columns
numeric_cols=numeric_cols.drop("longitude")
numeric_cols=numeric_cols.drop("latitude")
# numeric_cols=numeric_cols.drop("review_scores_rating")

# keep the rows have non negative numbers
df = merged_df.loc[(merged_df[numeric_cols] >= 0).all(axis=1)]
df.head()

,id,source,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,latitude,...,maximum_nights,number_of_reviews,review_scores_rating,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,date,available
0,108061,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,2010-12-16,"Asheville, NC",within an hour,100%,71%,35.6067,...,365,92,4.51,2,2,0,0,0.66,2023-03-19,f
1,108061,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,2010-12-16,"Asheville, NC",within an hour,100%,71%,35.6067,...,365,92,4.51,2,2,0,0,0.66,2023-03-20,f
2,108061,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,2010-12-16,"Asheville, NC",within an hour,100%,71%,35.6067,...,365,92,4.51,2,2,0,0,0.66,2023-03-21,f
3,108061,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,2010-12-16,"Asheville, NC",within an hour,100%,71%,35.6067,...,365,92,4.51,2,2,0,0,0.66,2023-03-22,f
4,108061,city scrape,Walk to stores/parks/downtown. Fenced yard/Pet...,320564,2010-12-16,"Asheville, NC",within an hour,100%,71%,35.6067,...,365,92,4.51,2,2,0,0,0.66,2023-03-23,f

In [15]:
# Add states column and only take the rows that are in USA
# df = df[df['host_location'].str.split(', ').str[2] == 'United States']
# df['host_state'] = df['host_location'].str.split(', ').str[1]

In [16]:
print(len(df), len(df.columns))

1001925 29

In [17]:
print(len(df), len(df.columns))
# review_rating 'review_scores_rating'

1001925 29

In [18]:
# rearrange the columns order
new_order=['id', 'name', 'price', 'date', 'available', 'room_type', 'accommodates', 'bedrooms', 'beds', 'amenities',  'latitude', 'longitude', 'property_type', 
           'host_id', 'host_since', 'host_location', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 
           'minimum_nights', 'maximum_nights', 'number_of_reviews', 'review_scores_rating', 'reviews_per_month', 
           'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 
           'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms',]

df = df.reindex(columns=new_order)
df.head()

,id,name,price,date,available,room_type,accommodates,bedrooms,beds,amenities,...,host_acceptance_rate,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,reviews_per_month,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-19,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,71%,30,365,92,4.51,0.66,2,2,0,0
1,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-20,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,71%,30,365,92,4.51,0.66,2,2,0,0
2,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-21,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,71%,30,365,92,4.51,0.66,2,2,0,0
3,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-22,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,71%,30,365,92,4.51,0.66,2,2,0,0
4,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-23,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,71%,30,365,92,4.51,0.66,2,2,0,0

In [19]:
# save to csv zipped file
df.to_csv('../data/processed/clean_airbnb.gz', compression='gzip', index=False)

In [20]:
# df=pd.read_csv("../data/processed/clean_airbnb.gz")
# df = df.astype({'price': 'float', 'latitude': 'float', 'latitude': 'float', 'latitude': 'float', 'longitude': 'float', 
#               'accommodates': 'int', 'bedrooms': 'float', 'beds': 'float', 'minimum_nights': 'int', 'maximum_nights': 'int', 
#               'number_of_reviews': 'int', 'calculated_host_listings_count': 'int', 'calculated_host_listings_count_entire_homes': 'int', 
#               'calculated_host_listings_count_private_rooms': 'int', 'calculated_host_listings_count_shared_rooms': 'int', 'reviews_per_month': 'float'})
# df['date'] = pd.to_datetime(df['date'])
# df.head()
# df.dtypes
# print(len(df), len(df.columns))

# df["review_rating"] = df["review_scores_rating"].fillna(0)