In [1]:
import pandas as pd
import numpy as np
import os
import glob
import altair as alt
import plotly.graph_objects as go
import plotly.express as px

In [2]:
df=pd.read_csv("../data/processed/clean_airbnb.gz")
df.head()

,id,name,price,date,available,room_type,accommodates,bedrooms,beds,amenities,...,host_acceptance_rate,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,reviews_per_month,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-19,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,71%,30,365,92,4.51,0.66,2,2,0,0
1,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-20,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,71%,30,365,92,4.51,0.66,2,2,0,0
2,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-21,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,71%,30,365,92,4.51,0.66,2,2,0,0
3,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-22,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,71%,30,365,92,4.51,0.66,2,2,0,0
4,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-23,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,71%,30,365,92,4.51,0.66,2,2,0,0

# Transform (Monthly Price by County In NC)

In [3]:
df=df[df['host_location'].str.split(', ').str[1] == 'NC']

In [4]:
df.shape

(761390, 28)

In [5]:
df['county'] = df['host_location'].str.split(', ').str[0]
df['county'].unique()

array(['Asheville', 'Fletcher', 'Winston-Salem', 'Arden', 'Wilmington',
       'Barnardsville', 'Fayetteville', 'Hendersonville', 'Woodfin',
       'Burlington', 'Rocky Mount', 'Weaverville', 'Old Fort',
       'Charlotte', 'Raleigh', 'Candler', 'Fairview', 'Pittsboro',
       'Wake Forest', 'Huntersville', 'Merritt', 'Topsail Beach',
       'Marshall', 'Elon', 'Chapel Hill', 'Carrboro', 'Black Mountain',
       'Harrisburg', 'Waynesville', 'Leicester', 'Apex', 'Concord',
       'Bent Creek', 'Greensboro', 'Elizabeth City', 'Clayton', 'Hickory',
       'Newland'], dtype=object)

In [6]:
df = df.set_index(pd.to_datetime(df['date']),drop=False)
df.head()

,id,name,price,date,available,room_type,accommodates,bedrooms,beds,amenities,...,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,reviews_per_month,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,county
date,,,,,,,,,,,,,,,,,,,,,
2023-03-19,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-19,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,30,365,92,4.51,0.66,2,2,0,0,Asheville
2023-03-20,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-20,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,30,365,92,4.51,0.66,2,2,0,0,Asheville
2023-03-21,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-21,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,30,365,92,4.51,0.66,2,2,0,0,Asheville
2023-03-22,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-22,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,30,365,92,4.51,0.66,2,2,0,0,Asheville
2023-03-23,108061,Walk to stores/parks/downtown. Fenced yard/Pet...,100.0,2023-03-23,f,Entire home/apt,2,1.0,1.0,"[""Coffee maker"", ""Cleaning products"", ""Extra p...",...,30,365,92,4.51,0.66,2,2,0,0,Asheville

In [7]:
monthly_mean = df.groupby([df.index.date, 'county'])['price'].agg(['mean', 'median','min','max'])
ummelted_df=monthly_mean.reset_index()

# Preview

In [8]:
ummelted_df=ummelted_df.rename(columns={"level_0":"date"})
ummelted_df

             date         county        mean  median    min     max
0      2023-03-19           Apex  207.333333   136.0  127.0   359.0
1      2023-03-19          Arden  124.463415    98.0   43.0   771.0
2      2023-03-19      Asheville  170.637333   128.0   10.0  6588.0
3      2023-03-19  Barnardsville  305.000000   305.0  267.0   343.0
4      2023-03-19     Bent Creek   99.000000    99.0   99.0    99.0
...           ...            ...         ...     ...    ...     ...
13865  2024-03-17    Waynesville  149.500000   149.5   99.0   200.0
13866  2024-03-17    Weaverville  176.666667   144.0   93.0   446.0
13867  2024-03-17     Wilmington  355.333333   200.0  141.0   725.0
13868  2024-03-17  Winston-Salem   92.500000    92.5   68.0   117.0
13869  2024-03-17        Woodfin  137.450000   124.0   52.0   325.0

[13870 rows x 6 columns]

In [11]:
alt.data_transformers.enable('json')

DataTransformerRegistry.enable('json')

In [18]:
selection = alt.selection_single(fields=['county'],name='Random')
color = alt.condition(selection,
                      alt.value('steelblue'),
                      alt.value('lightgray'))

bar=(alt.Chart(ummelted_df)
 .mark_bar()
 .encode(y='sum(mean):Q',
         x=alt.X('county:N',
         sort=alt.EncodingSortField(field='mean', op='mean', 
                            order='descending'),
         #tooltip=['mean(mean)','median(mean)','min(mean)','max(mean)']
         ),
         color=color
        )
 .interactive()
).add_selection(selection)


bar.title ="Total Revenue for Airbnb (NC State)"
bar.encoding.x.title = 'County'
bar.encoding.y.title = 'Total Revenue in Year 2023'



color2 = alt.condition(selection,
                      alt.Color('county:N',title="Total Revenue"),
#                       alt.value('steelblue'),
                      alt.value('lightgray'))

line1=(alt.Chart(ummelted_df)
 .mark_line(point=True)
 .encode(x=alt.X('month(date):T'),
         y='sum(mean):Q',
         color=color2
        )
)

line1.title ="Total Revenue for Airbnb (NC State)"
line1.encoding.x.title = 'Month'
line1.encoding.y.title = 'Aotal Revenue in Month(s)'
bar | line1

alt.HConcatChart(...)